layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 12
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: Kelvin Paa Kwesi Adjei
  # hackerrank: kadjei1
  # instagram: kaypeekay_
  # keybase: your_username
  # linkedin: Kelvin Adjei
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: 13071432
  # telegram: your_username
  # twitter: Kelvin Adjei
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Web design
    web_url: https://www.codecademy.com
    image_url: https://www.octalsoftware.com/blog/public/storage/img/blog/1584082601Web-development-designing-Anvar-Freelancer-1%20(1).png

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png

  - name: Arduino
    web_url: https://www.arduino.cc/en/Tutorial/HomePage
    image_url: https://www.arduino.cc/en/uploads/Trademark/ArduinoCommunityLogo.png

  - name: FPGA
    web_url: https://www.rs-online.com/designspark/a-gentle-introduction-to-fpga-programming
    image_url: https://cdn.lynda.com/course/794136/794136-637286265610922342-16x9.jpg
